// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzUtLhqstRYZcEdvX8_xXxtSlxlHfisYo',
    appId: '1:905726736218:web:0f61ab9b2b217980a3e563',
    messagingSenderId: '905726736218',
    projectId: 'flash2mart',
    authDomain: 'flash2mart.firebaseapp.com',
    storageBucket: 'flash2mart.firebasestorage.app',
    measurementId: 'G-F649B7R628',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdd5geZH9ZKDqiGOZpgaOGt2jJJrM3qzU',
    appId: '1:905726736218:android:3489de9fa61ca4c9a3e563',
    messagingSenderId: '905726736218',
    projectId: 'flash2mart',
    storageBucket: 'flash2mart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQmmntTpl4J1pb_b7WXqYdV9LtELXk4kg',
    appId: '1:905726736218:ios:b76ea3f706b4cdd3a3e563',
    messagingSenderId: '905726736218',
    projectId: 'flash2mart',
    storageBucket: 'flash2mart.firebasestorage.app',
    iosClientId: '905726736218-d0vaa1eeeiag7ocbnovkanghe4dt2eld.apps.googleusercontent.com',
    iosBundleId: 'com.example.flash2martDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQmmntTpl4J1pb_b7WXqYdV9LtELXk4kg',
    appId: '1:905726736218:ios:b76ea3f706b4cdd3a3e563',
    messagingSenderId: '905726736218',
    projectId: 'flash2mart',
    storageBucket: 'flash2mart.firebasestorage.app',
    iosClientId: '905726736218-d0vaa1eeeiag7ocbnovkanghe4dt2eld.apps.googleusercontent.com',
    iosBundleId: 'com.example.flash2martDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzUtLhqstRYZcEdvX8_xXxtSlxlHfisYo',
    appId: '1:905726736218:web:e53869a27cac980da3e563',
    messagingSenderId: '905726736218',
    projectId: 'flash2mart',
    authDomain: 'flash2mart.firebaseapp.com',
    storageBucket: 'flash2mart.firebasestorage.app',
    measurementId: 'G-T0NWSKBS2G',
  );
}
